# Generated by Django 5.1.6 on 2025-03-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_created_at_category_updeted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updeted_at',
            new_name='updated_at',
        ),
    ]
