# Generated by Django 5.1.6 on 2025-03-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_age_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
