# Generated by Django 5.1.6 on 2025-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_characteristics_characteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='show_in_filters',
            field=models.BooleanField(default=False),
        ),
    ]
