# Generated by Django 5.1.6 on 2025-03-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_age_restricted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carecteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carecteristics', to='products.category')),
            ],
            options={
                'verbose_name': 'carecteristic',
                'verbose_name_plural': 'carecteristics',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_ca3f2c_idx'), models.Index(fields=['category'], name='products_ca_categor_15ab74_idx')],
            },
        ),
    ]
