# Generated by Django 5.1.6 on 2025-03-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_age_restricted',
        ),
        migrations.AddField(
            model_name='category',
            name='is_age_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
