# Generated by Django 5.1.6 on 2025-03-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_is_age_restricted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_age_restricted',
            field=models.BooleanField(default=False, verbose_name='Продукт 18+'),
        ),
    ]
